### ISSUE TITLE
The extension should be defined at root, scene, or node level

### ISSUE THREAD

**Issue by vpenades** [takahirox/EXT_skin_humanoid#2]
Hi, I've just stumbled upon your extension, and I wanted to share my thoughts;

The extension is tied to the Skin object, which means it assumes all characters are made of only one skin.

This might not always be the case; it's not common, but it's possible to have multiple skins to form a single character, in which case, you would need one extension per skin, duplicating the maps?

There might also be characters not made of skins at all, like robots, where the robot mesh parts are tied to each node directly. Or characters with missing bones in the skin hierarchy, because all the nodes involved in the animation don't need to be used in the skin (RayMan character, would miss the elbow and knee bones in the skin) 

Finally, the skin object is just a way to "bind" the a skeleton to a mesh, but the skin itself does not affect the nodes in any way. And since this extension is intended to handle how node animations should be interpreted

I agree that like 90% of characters around use a single skin, but I think proposing an EXT_ extension needs to be more robust and cover 100% of the cases, that's why, IMHO skin is not a good place for the extension.

Instead, I would define the extension at the Scene level, or even at the Root level.

Another option would be to add the extension directly to each Node, like you do with the animation channels. Actually, I think that's what would make more sense.

**Comment by takahirox** [comment]
Hi thanks for the comment.

> The extension is tied to the Skin object, which means it assumes all characters are made of only one skin.

Yes, I added the restriction that a skeleton consists of a single `skin` for simplicity.

If we want to remove this resriction, I would think of

* `skin.skeleton` **MUST** be defined for `skins` that are (or whose joints are) reffered by this extension
  * I assume that `skins` refer to the same skeleton (common root) if a single humanoid skeleton consists of multiple `skins`. Is this assumption correct?
* define the extension at note referred by `skin.skeleton`

For example

```json
"skins": {
  [
    "joints": [1, 2, ...],
    "skeleton": 0
  ],
  [
    "joints": [3, 4, ...],
    "skeleton": 0
  ]
},
"nodes": {
  [
    // skeleton common root
    ...,
    "extensions": {
      "EXT_skin_humanoid": {
        "humanoidBones": {
          // node indices, not indices in `skin.joints`
          "leftShoulder": 1,
          "leftUpperArm": 2
          "rightShoulder": 3,
          "rightUpperArm": 4,
          ..
        }
      }
    }
  ],
  ...
}
```

The idea is from my experience that the implementation can often be simpler if an extension is defined at a place where strongly associated, so at skeleton node rather than scene or root.

**Comment by vpenades** [comment]
> The idea is from my experience that the implementation can often be simpler if an extension is defined at a place where strongly associated, so at skeleton node rather than scene or root.

In my implementation, the skin object is just a helper structure used at rendering time. At the time it is used, all the node transformation must be already evaluated, so any "humanoid" bindings must have happened way before the skin object is used.

Since your extension is designed to control how the node tranformations are calculated (motion retargeting) it makes sense to put the extension where the transformation evaluation happens (in the nodes)

I think that requiring a "skeleton" in the skin is a bit redundant; By setting the extension in the root node, you're already tagging it as the "humanoid root".

----

For clarification, I've writen some pseudo code on how a scene is evaluated and drawn in two steps:

1- Evaluation (final transformations are stored on each node as _Evaluated Transforms_
- For each node
  - Does the root of this node have EXT_Node_Humanoid ?
    - Yes:
      - Is this node an Humanoid Node (ex: leftShoulder) ?
        - Yes:
          - Use transformation of motion retargeted LeftShoulder, and move to next node.
  - Does it have animation?
    - Yes:
      - Evaluate the animation curves and get a tranform for it, and move to next node
  - Default:
    - Use node default transform.

2 - Rendering
- For each node
  - Does it have a mesh?
    -  No: skip to next node
  - Does it have a skin?
    - No: use Node _Evaluated Transform_ to draw the mesh
    - Yes: use skin node _Evaluated Transforms_ to draw the mesh

----

In order to evaluate the humanoid transforms, everything boils down to know if a given node is a "LeftShoulder" or any other defined Humanoid bone. It would be easier if Node 7 has its own extension that tells it's a "LeftShoulder", otherwise, for each node I have to traverse down to the root where the EXT_Humanoid is located, to see if the currently evaluated node is a humanoid bone or not.

As you can see, the skin, in the 2nd step, does not require any knowledge of the extension, it just maps the _evaluated transforms_ of the nodes to the vertex shader constants.

Certainly, other engines might evaluate the scene in a different way, I guess your current proposal is designed to meet the requirements of some engines (godot?)  that interpret a Humanod = single Skeleton = single skin , so they evaluate the node transforms at the skin level and not at the scene level.

**Comment by takahirox** [comment]
I revisited. I started to think that

* I don't want to add a limitation that a skeleton should consist of a single skin and
* Simpler structure should be preferrable for easier and simpler implementation

Then, the current design may not be good because it restricts that a single skeleton should consist of a single skin. Also, defining the extension at a node reffered by `skin.skeleton` may be a bit tricky. The definition should be easily found.

Now, I think defining at scene (or glTF root?) would be the simplest.

**Comment by takahirox** [comment]
I revisited. I started to think that the extension would be good to be defined at glTF root level.

A humanoid skeleton consists of multiple `skins` and `nodes` and is more complex than I first thought. It wouldn't be good to be defined at `node` or `skin` because the definition can be scattered. glTF root level would be a good place similar to where `skins`, `meshes` in the core or the lights extension are defined.

The definition would become like

```json
"extensions": {
    "EXT_skin_humanoid": {
        "humanoidSkeletons": [
            {
                "rootNode": 0,
                "humanoidBones": {
                    // node indices
                    "leftShoulder": 1,
                    "leftUpperArm": 2,
                    "rightShoulder": 3,
                    "rightUpperArm": 4,
                    ...
                },
            },
            {
                "rootNode": 10,
                "humanoidBones": {
                    "leftShoulder": 11,
                    "leftUpperArm": 12,
                    "rightShoulder": 13,
                    "rightUpperArm": 14,
                    ...
                },
            }
        ]
    }
},
```

There may be two or more humanoid skeletons in a fileso the `extensions.EXT_skin_humanoid.humanoidSkeletons` takes an array.

**Comment by vpenades** [comment]
I like this one way more, it is less instrusive and I think it's easier to use for motion retargeting.

I am tempted to add more information per bone, but I think your extension is good as it is defined right now, because it
defines a skeleton as a whole, and the hierarchical relationship between bones.

If bones require additional information like axis alignment or constraints,  that information can be provided by another extension placed in every node.

**Comment by takahirox** [comment]
> If bones require additional information like axis alignment or constraints, that information can be provided by another extension placed in every node.

I guess you refer to the Default pose section? I want this extension to be minimal set that is enough to allow to define standard humanoid skeleton and its animation retargetting. More extra constraints should be defined in another extension as you mentioned.
