### ISSUE TITLE
Missing leftEye, rightEye, jaw?

### ISSUE THREAD

**Issue by robertlong** [takahirox/EXT_skin_humanoid#8]
Hey @takahirox! This is an awesome spec and a really important missing piece of the glTF avatar ecosystem. Will this spec include the leftEye, rightEye, and jaw bones in the VRM humanoid skeleton definition? https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/humanoid.md#head

**Comment by takahirox** [comment]
Hi @robertlong, thanks for asking about it.

>  Will this spec include the leftEye, rightEye, and jaw bones in the VRM humanoid skeleton definition?

It is what I'm thinking whether the spec should include them. I want the extension and bone set to be minimal as they are enough to define standard humanoid skeleton and its animation retargetting. I'm wondering whether eyes and jaw are needed in standard humanoid skeleton. I just haven't researched the existing standard humanoid skeleton specs yet.

If they are in the existing major standard humanoid skeletons, no reason to block to include them.

**Comment by vpenades** [comment]
here's my opinion about this:

in most models I've seen the eyes are handled by bones, but again I don't know if there's a standard for axis alignment.

I think the jaw is trickier... because the whole point of moving the jaw is to animate the mouth, and here's where we enter into uncharted territory.

There's absolutely no standard for facial animation, it can be completely done with bones,  with morph targets, or a combination of both.

If I would be me, and given defining the joints can be optional, I would include the eyes because it's almost guaranteed they're going to be animated with bones.

I would not include the jaw because there's no point of include it if you don't include the mouth too.

In the future if someone developes a standard for face animation, we cound define some kind of rule where the face animation should override the animation of eyes in this extension.

**Comment by takahirox** [comment]
> In the future if someone developes a standard for face animation, we cound define some kind of rule where the face animation should override the animation of eyes in this extension.

In my mind, facial animation is out of scope from this extension. If it's done with bones another extension can be defined that may extend this extension.

**Comment by takahirox** [comment]
From #10, I got to know that VRM skeleton is based on the Unity one and eyes and jaw are in the Uniti one. I'm thinking of adding them to the skeleton in this extension.

**Comment by vpenades** [comment]
> From #10, I got to know that VRM skeleton is based on the Unity one and eyes and jaw are in the Uniti one. I'm thinking of adding them to the skeleton in this extension.

I agree, it there's standards already defined, it's better to follow them.
